version: '3.8'
services:
  # elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    hostname: elasticsearch
    restart: unless-stopped
    user: '1000:0'
    ports:
      #- '0.0.0.0:9200:9200'
      - ${ES_PORT}:9200
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    mem_limit: ${MEM_LIMIT}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/log:/usr/share/elasticsearch/logs
      - ./elasticsearch/certs:/usr/share/elasticsearch/config/certs
  
  # Cortex
  cortex:
    image: thehiveproject/cortex:${CORTEX_VERSION}
    container_name: cortex
    hostname: cortex
    restart: unless-stopped
    volumes:
      - ./cortex/config:/etc/cortex
      - ./cortex/log:/var/log/cortex
      - ./cortex/jobs:/tmp/cortex-jobs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch
    ports:
      - ${CORTEX_PORT}:9001
  
  # Minio
  minio:
    container_name: minio
    image: quay.io/minio/minio:${MINIO_VERSION}
    hostname: minio
    restart: unless-stopped
    ports:
      - ${MINIO_PORT}:9002
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER_REDIRECT_URL=https://minio
      - MINIO_DOMAIN=minio
      - VIRTUAL_HOST=minio
      - LETSENCRYPT_HOST=minio
    command: server --console-address ":9002" /data
    # command: ["minio", "server", "/data", "--console-address", ":9001"]
    volumes:
      - ./minio/data:/data
    

