version: '3.8'
services:
  # elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    hostname: elasticsearch
    restart: unless-stopped
    user: '1000:0'
    ports:
      #- '0.0.0.0:9200:9200'
      - ${ES_PORT}:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    mem_limit: ${MEM_LIMIT}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/log:/usr/share/elasticsearch/logs
      - ./elasticsearch/certs:/usr/share/elasticsearch/config/certs
      
  # Minio
  minio:
    container_name: minio
    image: quay.io/minio/minio:${MINIO_VERSION}
    hostname: minio
    restart: unless-stopped
    ports:
      #- "9001:9001"
      - ${MINIO_PORT}:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER_REDIRECT_URL=https://minio
      - MINIO_DOMAIN=minio
      - VIRTUAL_HOST=minio
      - LETSENCRYPT_HOST=minio
    command: server --console-address ":9001" /data
    # command: ["minio", "server", "/data", "--console-address", ":9001"]
    volumes:
      - ./minio/data:/data
    

